### ISSUE TITLE
adding other providers?

### ISSUE THREAD

**Issue by gregsadetsky** [veloplanner/map-matrix#2]
congrats on this great project!

I work at Radar and we have a cost effective alternative to Google Maps and Mapbox -- [see here](https://radar.com/documentation/maps/maps)

would you be open to a PR that would add support for our maps? it would mostly consist of:
- an additional input + some copy in the API Keys modal
- an additional choice in the source select menu
- obviously all required classes/changes

our map is based on the same standard pbf vector tiles, so the additional code in Map.tsx would be pretty minimal (i.e. it would use the same `MapGL` component as you're using now)

cheers!

**Comment by caspg** [comment]
@gregsadetsky Of course! More the merrier.
